# Generated by Django 5.1.7 on 2025-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepiececards',
            name='precio_local',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
