# Generated by Django 5.1.7 on 2025-05-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_onepiececards_precio_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenOnepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.onepiececards')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_onepiece', to='Productos.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.pokemoncard')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pokemon', to='Productos.ordencompra')),
            ],
        ),
    ]
