# Generated by Django 5.1.7 on 2025-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_carrito_ordencompra_itemcarrito_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
