# Generated by Django 5.1.7 on 2025-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
