# Generated by Django 5.1.7 on 2025-05-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_remove_itemcarrito_producto_itemcarrito_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
