# Generated by Django 5.1.7 on 2025-05-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_remove_detalleorden_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
