# Generated by Django 5.1.7 on 2025-05-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
