# Generated by Django 5.1.7 on 2025-05-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
