# Generated by Django 5.1.7 on 2025-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_detalleorden_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
