# Generated by Django 5.1.7 on 2025-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_detalleorden_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='onepieceprods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='onepiece/')),
            ],
        ),
        migrations.CreateModel(
            name='pokemonprods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('set', models.CharField(max_length=255)),
                ('rareza', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pokemon/')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Categoria_producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
